# -*- coding: utf-8 -*-
"""jogodavelha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TR1icLyBlDJU5J8QhqyatxV6xOtYVEjh
"""

tabuleiro =["1","2","3",
            "4","5","6",
            "7","8","9"]

jogador_atual = "X"

def mostrar_tabuleiro():
  print()
  print(tabuleiro[0],"|",tabuleiro[1],"|",tabuleiro[2])
  print("--+---+--")
  print(tabuleiro[3],"|",tabuleiro[4],"|",tabuleiro[5])
  print("--+---+--")
  print(tabuleiro[6],"|",tabuleiro[7],"|",tabuleiro[8])
  print()

def verificar_vitoria():
  combinacoes = [
      [0,1,2], [3,4,5], [6,7,8], #vitoria por linha
      [0,3,6], [1,4,7], [2,5,8], #vitoria por coluna
      [0,4,8], [2,4,6]#vitoria por diagonal
  ]

  for c in combinacoes:
    if tabuleiro[c[0]] == tabuleiro[c[1]] == tabuleiro[c[2]]:
      return True

  return False

def verificar_empate():
  for espaco in tabuleiro:
    if espaco not in ["X","O"]:
      return False

  return True

while True:
  mostrar_tabuleiro()

  jogada = input(f"jogador{jogador_atual}, escolha uma posição atual: ")

  if jogada not in tabuleiro:
    print("jogada invalida escolha outra posição")
    continue

  indice = tabuleiro.index(jogada)
  tabuleiro[indice] = jogador_atual

  if veri56ficar_vitoria():
    mostrar_tabuleiro()
    print(f"jogador {jogador_atual} venceu!")
    break

  if verificar_empate():
    mostrar_tabuleiro()
    print("Deu velha! empate")
    break
  #troca de jogador
  if jogador_atual == "0":
    jogador_atual = "x"
  else:
    jogador_atual = "X"

